common: &common
  adapter: postgresql
  encoding: utf8
  database: big-brother
  username: florentangles
  password:
  host: localhost

development:
  <<: *common

test: &test
  <<: *common

production:
  <<: *common

